"""
Pre-generated Task Library for LifeMicro
AI-generated once, used forever - no ongoing API costs
"""

TASK_LIBRARY = {
    "fitness": [
        {"title": "10 Jumping Jacks", "description": "Get your blood pumping with quick jumping jacks. Feel the energy!", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Wall Push-ups", "description": "Do 10 wall push-ups. Great for building upper body strength anywhere.", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Stretch Break", "description": "Stand up and stretch your arms overhead, then touch your toes. Hold each for 10 seconds.", "time_estimate": "2 min", "reward_amount": 5},
        {"title": "Desk Squats", "description": "Do 10 squats right at your desk. Your legs will thank you!", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Walk 500 Steps", "description": "Take a quick walk around. Count 500 steps or walk for 5 minutes.", "time_estimate": "5 min", "reward_amount": 15},
        {"title": "Calf Raises", "description": "Do 20 calf raises while standing. Great for leg strength!", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Neck Rolls", "description": "Gently roll your neck in circles, 5 times each direction. Release tension!", "time_estimate": "1 min", "reward_amount": 3},
        {"title": "Plank Hold", "description": "Hold a plank position for 30 seconds. Core strength builder!", "time_estimate": "1 min", "reward_amount": 10},
        {"title": "Arm Circles", "description": "Extend arms and make 20 small circles forward, then backward.", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "High Knees", "description": "March in place with high knees for 30 seconds. Great cardio burst!", "time_estimate": "1 min", "reward_amount": 8},
        {"title": "Shoulder Shrugs", "description": "Shrug your shoulders up to your ears, hold 3 seconds, release. Repeat 10 times.", "time_estimate": "1 min", "reward_amount": 3},
        {"title": "Stair Climb", "description": "Walk up and down stairs for 3 minutes. No stairs? Do step-ups on a sturdy surface.", "time_estimate": "3 min", "reward_amount": 12},
        {"title": "Toe Touches", "description": "Stand and reach for your toes 15 times. Great hamstring stretch!", "time_estimate": "2 min", "reward_amount": 5},
        {"title": "Wall Sit", "description": "Hold a wall sit position for 30 seconds. Feel the burn!", "time_estimate": "1 min", "reward_amount": 10},
        {"title": "Lunges", "description": "Do 10 alternating lunges. Step forward, lower, push back.", "time_estimate": "2 min", "reward_amount": 10},
        {"title": "Desk Dips", "description": "Do 10 tricep dips using your desk or chair. Build arm strength!", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Standing Side Stretch", "description": "Reach one arm overhead and lean to the side. Hold 15 seconds each side.", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "March in Place", "description": "March in place for 2 minutes. Keep those knees high!", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Wrist Circles", "description": "Rotate your wrists 10 times each direction. Prevents strain!", "time_estimate": "1 min", "reward_amount": 3},
        {"title": "Hip Circles", "description": "Stand and rotate your hips in big circles, 10 each direction.", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Burpees", "description": "Do 5 burpees. Squat, jump back, push-up, jump up. Full body workout!", "time_estimate": "2 min", "reward_amount": 15},
        {"title": "Drink Water", "description": "Drink a full glass of water right now. Hydration is key!", "time_estimate": "1 min", "reward_amount": 3},
        {"title": "Deep Breathing Walk", "description": "Walk for 3 minutes while taking deep, slow breaths.", "time_estimate": "3 min", "reward_amount": 10},
        {"title": "Balance Challenge", "description": "Stand on one foot for 30 seconds, then switch. Improves stability!", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Shadow Boxing", "description": "Throw punches in the air for 1 minute. Fun cardio!", "time_estimate": "1 min", "reward_amount": 8},
    ],
    
    "focus": [
        {"title": "Clear Your Desk", "description": "Take 2 minutes to organize your immediate workspace. Clear space, clear mind.", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "One Deep Breath", "description": "Take one very deep breath. Inhale for 4 seconds, hold for 4, exhale for 4.", "time_estimate": "1 min", "reward_amount": 3},
        {"title": "Set Today's Priority", "description": "Write down the ONE most important thing you need to do today.", "time_estimate": "2 min", "reward_amount": 10},
        {"title": "Close Unnecessary Tabs", "description": "Close all browser tabs you don't need right now. Digital declutter!", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "5-Minute Focus Sprint", "description": "Work on your most important task for exactly 5 minutes. No distractions.", "time_estimate": "5 min", "reward_amount": 15},
        {"title": "Phone on Silent", "description": "Put your phone on silent and face-down for the next 30 minutes.", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Brain Dump", "description": "Write down everything on your mind for 3 minutes. Get it out of your head!", "time_estimate": "3 min", "reward_amount": 10},
        {"title": "Pomodoro Start", "description": "Set a timer for 25 minutes and focus on one task until it rings.", "time_estimate": "25 min", "reward_amount": 25},
        {"title": "Review Your Goals", "description": "Read through your goals. Remind yourself why you're working hard.", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Eliminate One Distraction", "description": "Identify and remove one thing that's distracting you right now.", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Two-Minute Rule", "description": "Do one task that takes less than 2 minutes. Just get it done!", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Plan Tomorrow", "description": "Write down 3 things you'll accomplish tomorrow.", "time_estimate": "3 min", "reward_amount": 10},
        {"title": "Mindful Minute", "description": "Close your eyes and focus only on your breathing for 60 seconds.", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Inbox Zero Push", "description": "Process 5 emails right now. Reply, delete, or archive.", "time_estimate": "5 min", "reward_amount": 12},
        {"title": "Single-Task Challenge", "description": "Pick one task and do ONLY that for the next 10 minutes.", "time_estimate": "10 min", "reward_amount": 20},
        {"title": "Visualize Success", "description": "Close your eyes and visualize completing your most important task.", "time_estimate": "2 min", "reward_amount": 5},
        {"title": "Break a Task Down", "description": "Take a big task and break it into 3 smaller steps.", "time_estimate": "3 min", "reward_amount": 10},
        {"title": "Positive Affirmation", "description": "Say out loud: 'I am focused and productive.' Believe it!", "time_estimate": "1 min", "reward_amount": 3},
        {"title": "Workspace Reset", "description": "Reset your workspace to how it looks when you're most productive.", "time_estimate": "3 min", "reward_amount": 8},
        {"title": "Time Block", "description": "Block out 1 hour on your calendar for deep work today.", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Say No to One Thing", "description": "Decline or postpone one commitment that's not essential.", "time_estimate": "2 min", "reward_amount": 10},
        {"title": "Morning Intention", "description": "Set one clear intention for how you want to feel today.", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Progress Check", "description": "Review what you've accomplished so far today. Celebrate wins!", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Learn One Thing", "description": "Read one article or watch one video related to your work.", "time_estimate": "5 min", "reward_amount": 12},
        {"title": "Gratitude Pause", "description": "Think of one thing about your work that you're grateful for.", "time_estimate": "1 min", "reward_amount": 5},
    ],
    
    "business": [
        {"title": "Reply to One Email", "description": "Answer one important email you've been putting off.", "time_estimate": "3 min", "reward_amount": 10},
        {"title": "Network Outreach", "description": "Send a LinkedIn message or email to one professional contact.", "time_estimate": "3 min", "reward_amount": 12},
        {"title": "Learn Industry News", "description": "Read one article about your industry. Stay informed!", "time_estimate": "5 min", "reward_amount": 10},
        {"title": "Update Your LinkedIn", "description": "Add one new skill or update one section of your LinkedIn profile.", "time_estimate": "5 min", "reward_amount": 15},
        {"title": "Follow Up", "description": "Follow up with someone you met or contacted recently.", "time_estimate": "3 min", "reward_amount": 10},
        {"title": "Review Your Goals", "description": "Look at your business/career goals. Are you on track?", "time_estimate": "3 min", "reward_amount": 8},
        {"title": "Brainstorm Ideas", "description": "Write down 5 ideas for your business or career growth.", "time_estimate": "5 min", "reward_amount": 15},
        {"title": "Learn a Skill", "description": "Watch a 5-minute tutorial on a skill you want to improve.", "time_estimate": "5 min", "reward_amount": 12},
        {"title": "Organize Files", "description": "Organize one folder on your computer. Delete what you don't need.", "time_estimate": "5 min", "reward_amount": 10},
        {"title": "Send a Thank You", "description": "Send a thank you message to someone who helped you recently.", "time_estimate": "3 min", "reward_amount": 10},
        {"title": "Review Finances", "description": "Spend 5 minutes reviewing your business or personal finances.", "time_estimate": "5 min", "reward_amount": 12},
        {"title": "Competitor Check", "description": "Spend 5 minutes looking at what your competitors are doing.", "time_estimate": "5 min", "reward_amount": 10},
        {"title": "Update Resume", "description": "Add one recent accomplishment to your resume.", "time_estimate": "5 min", "reward_amount": 15},
        {"title": "Schedule a Meeting", "description": "Reach out to schedule a meeting with someone valuable.", "time_estimate": "3 min", "reward_amount": 10},
        {"title": "Professional Post", "description": "Share something valuable on LinkedIn or your professional platform.", "time_estimate": "5 min", "reward_amount": 12},
        {"title": "Pitch Practice", "description": "Practice your elevator pitch out loud for 2 minutes.", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Customer Outreach", "description": "Reach out to one customer or potential customer.", "time_estimate": "5 min", "reward_amount": 15},
        {"title": "Process Improvement", "description": "Identify one thing in your work process you could do better.", "time_estimate": "3 min", "reward_amount": 10},
        {"title": "Delegate Something", "description": "Identify one task you could delegate or automate.", "time_estimate": "3 min", "reward_amount": 10},
        {"title": "Celebrate a Win", "description": "Write down one recent business win, big or small.", "time_estimate": "2 min", "reward_amount": 5},
        {"title": "Ask for Feedback", "description": "Ask one colleague or customer for feedback on your work.", "time_estimate": "3 min", "reward_amount": 12},
        {"title": "Set a Deadline", "description": "Set a specific deadline for one task you've been avoiding.", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Mentor Moment", "description": "Share one piece of advice with someone less experienced.", "time_estimate": "5 min", "reward_amount": 12},
        {"title": "Review Metrics", "description": "Check one key metric for your business or work performance.", "time_estimate": "3 min", "reward_amount": 10},
        {"title": "Plan Next Week", "description": "Write down your top 3 priorities for next week.", "time_estimate": "5 min", "reward_amount": 12},
    ],
    
    "relationships": [
        {"title": "Send a Kind Text", "description": "Text a friend or family member something nice right now.", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Express Gratitude", "description": "Tell someone why you appreciate them. Be specific!", "time_estimate": "3 min", "reward_amount": 12},
        {"title": "Schedule a Call", "description": "Schedule a phone or video call with someone you miss.", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Compliment Someone", "description": "Give a genuine compliment to someone today.", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Listen Fully", "description": "Have a conversation where you only listen. Don't think about your response.", "time_estimate": "5 min", "reward_amount": 15},
        {"title": "Forgiveness Practice", "description": "Think of someone you need to forgive. Take a step toward letting go.", "time_estimate": "3 min", "reward_amount": 10},
        {"title": "Plan a Date", "description": "Plan a date or hangout with your partner, friend, or family member.", "time_estimate": "5 min", "reward_amount": 12},
        {"title": "Write a Note", "description": "Write a short handwritten note to someone you care about.", "time_estimate": "5 min", "reward_amount": 15},
        {"title": "Ask About Their Day", "description": "Ask someone how their day is going and really listen to the answer.", "time_estimate": "3 min", "reward_amount": 8},
        {"title": "Share a Memory", "description": "Share a happy memory with someone who was there.", "time_estimate": "3 min", "reward_amount": 10},
        {"title": "Offer Help", "description": "Offer to help someone with something they're working on.", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Put Phone Away", "description": "Put your phone away during your next conversation. Be present.", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Reconnect", "description": "Reach out to someone you haven't talked to in a while.", "time_estimate": "3 min", "reward_amount": 12},
        {"title": "Say I Love You", "description": "Tell someone important that you love them.", "time_estimate": "1 min", "reward_amount": 8},
        {"title": "Small Gesture", "description": "Do a small act of kindness for someone. Make their day!", "time_estimate": "5 min", "reward_amount": 15},
        {"title": "Quality Time", "description": "Spend 10 minutes of undivided attention with someone.", "time_estimate": "10 min", "reward_amount": 20},
        {"title": "Apologize", "description": "If you owe someone an apology, now's the time. Be sincere.", "time_estimate": "3 min", "reward_amount": 15},
        {"title": "Boundary Setting", "description": "Set one healthy boundary in a relationship that needs it.", "time_estimate": "5 min", "reward_amount": 15},
        {"title": "Check In", "description": "Check in on someone who might be going through a hard time.", "time_estimate": "3 min", "reward_amount": 12},
        {"title": "Photo Memory", "description": "Send someone a photo that reminds you of a good time together.", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Verbal Appreciation", "description": "Tell someone specifically what you admire about them.", "time_estimate": "2 min", "reward_amount": 10},
        {"title": "Make Plans", "description": "Don't just say 'let's hang out' - set an actual date and time.", "time_estimate": "3 min", "reward_amount": 10},
        {"title": "Family Call", "description": "Call a family member you haven't spoken to recently.", "time_estimate": "5 min", "reward_amount": 15},
        {"title": "Be Vulnerable", "description": "Share something real about how you're feeling with someone you trust.", "time_estimate": "5 min", "reward_amount": 15},
        {"title": "Random Act of Kindness", "description": "Do something kind for a stranger today.", "time_estimate": "5 min", "reward_amount": 12},
    ],
    
    "spiritual": [
        {"title": "Mindful Breathing", "description": "Take 10 deep, slow breaths. Focus only on your breathing.", "time_estimate": "2 min", "reward_amount": 5},
        {"title": "Gratitude List", "description": "Write down 3 things you're grateful for right now.", "time_estimate": "3 min", "reward_amount": 10},
        {"title": "Nature Moment", "description": "Step outside and observe nature for 2 minutes. No phone.", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Meditation Minute", "description": "Close your eyes and sit in silence for 60 seconds.", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Journaling", "description": "Write freely about your thoughts and feelings for 5 minutes.", "time_estimate": "5 min", "reward_amount": 12},
        {"title": "Body Scan", "description": "Close your eyes and notice how each part of your body feels.", "time_estimate": "3 min", "reward_amount": 8},
        {"title": "Affirmation", "description": "Repeat a positive affirmation 5 times. Believe it.", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Forgiveness", "description": "Think of someone you need to forgive. Send them love mentally.", "time_estimate": "3 min", "reward_amount": 10},
        {"title": "Present Moment", "description": "Notice 5 things you can see, 4 you can hear, 3 you can feel.", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Read Something Inspiring", "description": "Read a quote, verse, or passage that inspires you.", "time_estimate": "3 min", "reward_amount": 8},
        {"title": "Send Love", "description": "Think of 3 people and mentally send them love and good wishes.", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Digital Sunset", "description": "Turn off screens for the next 30 minutes. Be present.", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Pray or Reflect", "description": "Spend 3 minutes in prayer or quiet reflection.", "time_estimate": "3 min", "reward_amount": 10},
        {"title": "Mindful Walk", "description": "Take a short walk focusing only on each step.", "time_estimate": "5 min", "reward_amount": 12},
        {"title": "Let Go", "description": "Identify one worry. Visualize releasing it like a balloon.", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Sunrise/Sunset", "description": "Watch the sunrise or sunset. Just observe.", "time_estimate": "5 min", "reward_amount": 12},
        {"title": "Loving Kindness", "description": "Repeat: 'May I be happy. May I be healthy. May I be at peace.'", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Declutter Mind", "description": "Write down everything worrying you, then close the notebook.", "time_estimate": "5 min", "reward_amount": 12},
        {"title": "Connect with Silence", "description": "Sit in complete silence for 3 minutes. No music, no talking.", "time_estimate": "3 min", "reward_amount": 10},
        {"title": "Count Blessings", "description": "Count 10 blessings in your life, big or small.", "time_estimate": "3 min", "reward_amount": 10},
        {"title": "Earth Connection", "description": "Stand barefoot on grass or earth for 2 minutes if possible.", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Self-Compassion", "description": "Say to yourself: 'I am doing my best, and that is enough.'", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Sacred Reading", "description": "Read from a spiritual or philosophical text that guides you.", "time_estimate": "5 min", "reward_amount": 12},
        {"title": "Evening Reflection", "description": "Reflect on your day. What went well? What are you grateful for?", "time_estimate": "5 min", "reward_amount": 12},
        {"title": "Set an Intention", "description": "Set one intention for how you want to show up today.", "time_estimate": "2 min", "reward_amount": 8},
    ],
    
    "creativity": [
        {"title": "Doodle Break", "description": "Grab a pen and doodle whatever comes to mind for 3 minutes.", "time_estimate": "3 min", "reward_amount": 8},
        {"title": "Write 3 Ideas", "description": "Write down 3 creative ideas. They don't have to be good!", "time_estimate": "3 min", "reward_amount": 10},
        {"title": "Take a Photo", "description": "Take a creative photo of something around you.", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Listen to New Music", "description": "Listen to a song from a genre you don't usually explore.", "time_estimate": "4 min", "reward_amount": 8},
        {"title": "Word Association", "description": "Pick a random word and write 10 words it makes you think of.", "time_estimate": "2 min", "reward_amount": 5},
        {"title": "Describe Your Surroundings", "description": "Write a creative description of where you are right now.", "time_estimate": "3 min", "reward_amount": 10},
        {"title": "Color Something", "description": "Color, paint, or sketch something for 5 minutes.", "time_estimate": "5 min", "reward_amount": 12},
        {"title": "Creative Observation", "description": "Look at an ordinary object and think of 5 unusual uses for it.", "time_estimate": "3 min", "reward_amount": 10},
        {"title": "Write a Haiku", "description": "Write a haiku (5-7-5 syllables) about your current mood.", "time_estimate": "3 min", "reward_amount": 10},
        {"title": "Mind Map", "description": "Create a mind map about a topic you're interested in.", "time_estimate": "5 min", "reward_amount": 12},
        {"title": "Rearrange Something", "description": "Rearrange items on your desk or in a room. Fresh perspective!", "time_estimate": "5 min", "reward_amount": 10},
        {"title": "Write a Story Start", "description": "Write the first paragraph of a story. Any story!", "time_estimate": "5 min", "reward_amount": 15},
        {"title": "Dream Capture", "description": "Write down a dream you remember, or imagine one.", "time_estimate": "3 min", "reward_amount": 8},
        {"title": "New Perspective", "description": "Look at something from a different angle. What do you notice?", "time_estimate": "2 min", "reward_amount": 5},
        {"title": "Playlist Creation", "description": "Create a short playlist for a specific mood or activity.", "time_estimate": "5 min", "reward_amount": 10},
        {"title": "Letter to Future Self", "description": "Write a short letter to yourself 1 year from now.", "time_estimate": "5 min", "reward_amount": 15},
        {"title": "Opposite Day", "description": "Think of a problem and brainstorm the opposite solution.", "time_estimate": "3 min", "reward_amount": 10},
        {"title": "Sensory Focus", "description": "Close your eyes and describe what you hear, smell, and feel.", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Quick Sketch", "description": "Sketch something in front of you in under 2 minutes.", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Metaphor Game", "description": "Describe your current mood as a weather pattern.", "time_estimate": "2 min", "reward_amount": 5},
        {"title": "Create a Meme", "description": "Think of a funny meme idea about your day.", "time_estimate": "3 min", "reward_amount": 8},
        {"title": "Recipe Invention", "description": "Invent a new recipe or food combination (don't have to make it!).", "time_estimate": "3 min", "reward_amount": 10},
        {"title": "Name Generator", "description": "Come up with 5 creative names for a fictional business.", "time_estimate": "3 min", "reward_amount": 8},
        {"title": "What If?", "description": "Write down 3 'What if?' questions about anything.", "time_estimate": "3 min", "reward_amount": 10},
        {"title": "Inspiration Hunt", "description": "Find one thing around you that inspires you. Why?", "time_estimate": "3 min", "reward_amount": 8},
    ],
    
    "health": [
        {"title": "Drink Water Now", "description": "Drink a full glass of water right now. Your body needs it!", "time_estimate": "1 min", "reward_amount": 3},
        {"title": "Posture Check", "description": "Sit up straight, shoulders back, feet flat. Hold for 30 seconds.", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Eye Break", "description": "Look away from screens. Focus on something 20 feet away for 20 seconds.", "time_estimate": "1 min", "reward_amount": 3},
        {"title": "Healthy Snack", "description": "Eat a piece of fruit or a handful of nuts.", "time_estimate": "3 min", "reward_amount": 8},
        {"title": "Stand Up", "description": "If you've been sitting, stand up and walk around for 2 minutes.", "time_estimate": "2 min", "reward_amount": 5},
        {"title": "Deep Breaths", "description": "Take 5 deep belly breaths. Inhale through nose, exhale through mouth.", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Sunshine Break", "description": "Get 5 minutes of sunlight if possible. Vitamin D boost!", "time_estimate": "5 min", "reward_amount": 10},
        {"title": "Mindful Eating", "description": "Eat your next meal slowly, savoring each bite.", "time_estimate": "10 min", "reward_amount": 15},
        {"title": "Track a Meal", "description": "Write down what you ate for your last meal. Awareness helps!", "time_estimate": "2 min", "reward_amount": 5},
        {"title": "Caffeine Check", "description": "If it's afternoon, skip the coffee. Choose water or tea instead.", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Screen-Free Zone", "description": "Designate no screens in your bedroom tonight.", "time_estimate": "1 min", "reward_amount": 8},
        {"title": "Veggie Goal", "description": "Commit to eating one extra serving of vegetables today.", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Sleep Intention", "description": "Set a bedtime for tonight and commit to it.", "time_estimate": "1 min", "reward_amount": 8},
        {"title": "Stress Release", "description": "Tense all muscles for 5 seconds, then release. Repeat 3 times.", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Limit Sugar", "description": "Skip one sugary item you would normally have today.", "time_estimate": "1 min", "reward_amount": 8},
        {"title": "Fresh Air", "description": "Step outside and take 10 deep breaths of fresh air.", "time_estimate": "2 min", "reward_amount": 5},
        {"title": "Health Appointment", "description": "Schedule a health checkup or appointment you've been putting off.", "time_estimate": "5 min", "reward_amount": 15},
        {"title": "Floss", "description": "Floss your teeth right now. Your gums will thank you!", "time_estimate": "2 min", "reward_amount": 5},
        {"title": "Wash Hands", "description": "Wash your hands properly for 20 seconds. Sing Happy Birthday!", "time_estimate": "1 min", "reward_amount": 3},
        {"title": "Alcohol-Free Evening", "description": "Skip alcohol tonight. Your sleep will be better!", "time_estimate": "1 min", "reward_amount": 10},
        {"title": "Stretch at Desk", "description": "Do 3 desk stretches: neck, shoulders, and back.", "time_estimate": "2 min", "reward_amount": 5},
        {"title": "Gratitude for Body", "description": "Thank your body for one thing it does well for you.", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "One Glass Less", "description": "If you drink soda, skip one serving today. Choose water!", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Mental Health Check", "description": "Rate your mood 1-10. What could improve it by 1 point?", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Early Wind-Down", "description": "Start your bedtime routine 15 minutes earlier tonight.", "time_estimate": "1 min", "reward_amount": 8},
    ],
}

# Energy-based modifiers
ENERGY_MODIFIERS = {
    "high": ["burpees", "high knees", "jumping", "walk", "stair"],
    "low": ["breathing", "stretch", "drink water", "mindful", "gratitude", "sit"],
    "medium": []  # No filter, use all
}

# Time-based filtering
TIME_FILTERS = {
    "5min": 5,
    "15min": 15,
    "30min": 30,
    "60min": 60,
}

def get_time_minutes(time_str: str) -> int:
    """Convert time estimate string to minutes"""
    if "min" in time_str:
        return int(time_str.replace(" min", "").replace("min", ""))
    return 5  # Default
