"""
Pre-generated Task Library for LifeMicro
AI-generated once, used forever - no ongoing API costs
~200 tasks per category = 1,400+ total tasks
"""

TASK_LIBRARY = {
    "fitness": [
        # Quick 1-min tasks (30 tasks)
        {"title": "10 Jumping Jacks", "description": "Get your blood pumping with quick jumping jacks. Feel the energy!", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Calf Raises", "description": "Do 20 calf raises while standing. Great for leg strength!", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Neck Rolls", "description": "Gently roll your neck in circles, 5 times each direction. Release tension!", "time_estimate": "1 min", "reward_amount": 3},
        {"title": "Arm Circles", "description": "Extend arms and make 20 small circles forward, then backward.", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "High Knees", "description": "March in place with high knees for 30 seconds. Great cardio burst!", "time_estimate": "1 min", "reward_amount": 8},
        {"title": "Shoulder Shrugs", "description": "Shrug your shoulders up to your ears, hold 3 seconds, release. Repeat 10 times.", "time_estimate": "1 min", "reward_amount": 3},
        {"title": "Drink Water", "description": "Drink a full glass of water right now. Hydration is key!", "time_estimate": "1 min", "reward_amount": 3},
        {"title": "Balance Challenge", "description": "Stand on one foot for 30 seconds, then switch. Improves stability!", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Shadow Boxing", "description": "Throw punches in the air for 1 minute. Fun cardio!", "time_estimate": "1 min", "reward_amount": 8},
        {"title": "Plank Hold", "description": "Hold a plank position for 30 seconds. Core strength builder!", "time_estimate": "1 min", "reward_amount": 10},
        {"title": "Wall Sit", "description": "Hold a wall sit position for 30 seconds. Feel the burn!", "time_estimate": "1 min", "reward_amount": 10},
        {"title": "Wrist Circles", "description": "Rotate your wrists 10 times each direction. Prevents strain!", "time_estimate": "1 min", "reward_amount": 3},
        {"title": "Hip Circles", "description": "Stand and rotate your hips in big circles, 10 each direction.", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Quick Squats", "description": "Do 10 quick bodyweight squats. Engage your glutes!", "time_estimate": "1 min", "reward_amount": 8},
        {"title": "Ankle Rotations", "description": "Rotate each ankle 10 times clockwise and counterclockwise.", "time_estimate": "1 min", "reward_amount": 3},
        {"title": "Chest Opener", "description": "Clasp hands behind back, lift chest, squeeze shoulder blades. Hold 20 seconds.", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Quick Pulse Squats", "description": "Get into squat position and pulse up and down 20 times.", "time_estimate": "1 min", "reward_amount": 8},
        {"title": "Standing Knee Hugs", "description": "Stand and hug each knee to your chest alternately, 10 each side.", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Torso Twists", "description": "Stand with hands on hips and twist your torso left and right 15 times.", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Quick Heel Drops", "description": "Rise on toes then drop heels quickly 20 times. Strengthens calves!", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Finger Stretches", "description": "Spread fingers wide, make fists, repeat 15 times. Good for typing hands!", "time_estimate": "1 min", "reward_amount": 3},
        {"title": "Eye-Level Punches", "description": "Punch straight ahead 30 times, alternating arms. Quick cardio!", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Standing Side Crunch", "description": "Stand and bring elbow to knee sideways, 10 each side.", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Quick Toe Taps", "description": "Tap your toes in front of you alternately, 40 total taps.", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Doorway Chest Stretch", "description": "Place arms on door frame and lean forward. Hold 30 seconds.", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Chair Leg Lifts", "description": "Sit and lift one leg straight out, hold 5 seconds. Alternate 5 times each.", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Quick Glute Squeezes", "description": "Squeeze your glutes tight for 5 seconds, release. Repeat 10 times.", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Standing Calf Stretch", "description": "Step back, press heel down, feel the stretch. 20 seconds each leg.", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Fist Pump Cardio", "description": "Pump your fists overhead rapidly for 30 seconds. Get that heart rate up!", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Quick Ab Engagement", "description": "Pull belly button to spine and hold for 30 seconds. Core activation!", "time_estimate": "1 min", "reward_amount": 5},

        # 2-min tasks (40 tasks)
        {"title": "Wall Push-ups", "description": "Do 10 wall push-ups. Great for building upper body strength anywhere.", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Stretch Break", "description": "Stand up and stretch your arms overhead, then touch your toes. Hold each for 10 seconds.", "time_estimate": "2 min", "reward_amount": 5},
        {"title": "Desk Squats", "description": "Do 10 squats right at your desk. Your legs will thank you!", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Toe Touches", "description": "Stand and reach for your toes 15 times. Great hamstring stretch!", "time_estimate": "2 min", "reward_amount": 5},
        {"title": "Lunges", "description": "Do 10 alternating lunges. Step forward, lower, push back.", "time_estimate": "2 min", "reward_amount": 10},
        {"title": "Desk Dips", "description": "Do 10 tricep dips using your desk or chair. Build arm strength!", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "March in Place", "description": "March in place for 2 minutes. Keep those knees high!", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Burpees", "description": "Do 5 burpees. Squat, jump back, push-up, jump up. Full body workout!", "time_estimate": "2 min", "reward_amount": 15},
        {"title": "Standing Side Stretch", "description": "Reach one arm overhead and lean to the side. Hold 15 seconds each side.", "time_estimate": "2 min", "reward_amount": 5},
        {"title": "Mountain Climbers", "description": "Do 20 mountain climbers. Hands on floor, alternate bringing knees to chest.", "time_estimate": "2 min", "reward_amount": 10},
        {"title": "Arm Swings", "description": "Swing arms forward and backward in big circles. 20 each direction.", "time_estimate": "2 min", "reward_amount": 5},
        {"title": "Reverse Lunges", "description": "Step backward into lunges, 8 each leg. Great for balance!", "time_estimate": "2 min", "reward_amount": 10},
        {"title": "Bicycle Kicks", "description": "Lie on back and do 30 bicycle crunches. Work those abs!", "time_estimate": "2 min", "reward_amount": 10},
        {"title": "Side Leg Raises", "description": "Stand and lift leg to side, 15 each leg. Hip strengthener!", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Tricep Stretches", "description": "Reach arm overhead, bend elbow, push with other hand. 30 seconds each.", "time_estimate": "2 min", "reward_amount": 5},
        {"title": "Jumping Squats", "description": "Do 10 jump squats. Squat down, explode up. Power move!", "time_estimate": "2 min", "reward_amount": 12},
        {"title": "Hip Flexor Stretch", "description": "Kneel and lunge forward to stretch hip flexors. 30 seconds each side.", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Plank to Push-up", "description": "From plank, go to push-up position and back, 10 times.", "time_estimate": "2 min", "reward_amount": 12},
        {"title": "Quad Stretch", "description": "Stand on one leg, pull other foot to glute. 30 seconds each leg.", "time_estimate": "2 min", "reward_amount": 5},
        {"title": "Butt Kicks", "description": "Jog in place bringing heels to your glutes. Do for 1 minute.", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Dead Bug Exercise", "description": "Lie on back, extend opposite arm and leg, 10 each side.", "time_estimate": "2 min", "reward_amount": 10},
        {"title": "Standing Knee Raises", "description": "Lift knees to hip height alternating. 20 total repetitions.", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Sumo Squats", "description": "Wide stance squats with toes out. Do 12 reps.", "time_estimate": "2 min", "reward_amount": 10},
        {"title": "Arm Pulses", "description": "Hold arms out to sides and pulse up and down. 40 pulses.", "time_estimate": "2 min", "reward_amount": 5},
        {"title": "Seated Spinal Twist", "description": "Sit and twist your torso, hold 20 seconds each side.", "time_estimate": "2 min", "reward_amount": 5},
        {"title": "Russian Twists", "description": "Sit with knees bent, lean back, twist side to side 20 times.", "time_estimate": "2 min", "reward_amount": 10},
        {"title": "Standing Hip Circles", "description": "Make big circles with one leg at a time, 10 each leg.", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Crunches", "description": "Lie on back and do 20 crunches. Engage your core!", "time_estimate": "2 min", "reward_amount": 10},
        {"title": "Lateral Arm Raises", "description": "Raise arms to shoulder height at sides, lower slowly. 15 reps.", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Donkey Kicks", "description": "On all fours, kick one leg back and up. 12 each side.", "time_estimate": "2 min", "reward_amount": 10},
        {"title": "Forward Fold", "description": "Bend at hips, reach for floor, relax neck. Hold 1 minute.", "time_estimate": "2 min", "reward_amount": 5},
        {"title": "Cross-Body Shoulder Stretch", "description": "Pull arm across chest, hold 30 seconds each arm.", "time_estimate": "2 min", "reward_amount": 5},
        {"title": "Knee Push-ups", "description": "Do 12 push-ups on your knees. Great modification!", "time_estimate": "2 min", "reward_amount": 10},
        {"title": "Standing Back Extension", "description": "Place hands on lower back and lean back slightly. Hold 30 seconds.", "time_estimate": "2 min", "reward_amount": 5},
        {"title": "Quick Step-ups", "description": "Step up and down on a step or sturdy surface 20 times.", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Hamstring Curls", "description": "Stand and curl one heel toward glute, 15 each leg.", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Bird Dog", "description": "On all fours, extend opposite arm and leg. 8 each side.", "time_estimate": "2 min", "reward_amount": 10},
        {"title": "Seated Forward Bend", "description": "Sit with legs extended, reach for toes. Hold 1 minute.", "time_estimate": "2 min", "reward_amount": 5},
        {"title": "Inchworms", "description": "Walk hands out to plank, walk back, stand. 5 repetitions.", "time_estimate": "2 min", "reward_amount": 10},
        {"title": "Butterfly Stretch", "description": "Sit with soles together, gently press knees down. Hold 1 minute.", "time_estimate": "2 min", "reward_amount": 5},

        # 3-5 min tasks (50 tasks)
        {"title": "Stair Climb", "description": "Walk up and down stairs for 3 minutes. No stairs? Do step-ups on a sturdy surface.", "time_estimate": "3 min", "reward_amount": 12},
        {"title": "Deep Breathing Walk", "description": "Walk for 3 minutes while taking deep, slow breaths.", "time_estimate": "3 min", "reward_amount": 10},
        {"title": "Walk 500 Steps", "description": "Take a quick walk around. Count 500 steps or walk for 5 minutes.", "time_estimate": "5 min", "reward_amount": 15},
        {"title": "Full Body Stretch Routine", "description": "Stretch neck, shoulders, back, hips, and legs. 30 seconds each.", "time_estimate": "5 min", "reward_amount": 15},
        {"title": "Dance Break", "description": "Put on your favorite song and dance for the whole thing!", "time_estimate": "4 min", "reward_amount": 12},
        {"title": "Power Walk", "description": "Walk as fast as you can for 5 minutes. Get that heart pumping!", "time_estimate": "5 min", "reward_amount": 15},
        {"title": "Yoga Flow", "description": "Do 5 sun salutations. Flow through the poses mindfully.", "time_estimate": "5 min", "reward_amount": 15},
        {"title": "Jump Rope (Imaginary)", "description": "Pretend you have a jump rope and jump for 3 minutes.", "time_estimate": "3 min", "reward_amount": 12},
        {"title": "Circuit: Squats, Lunges, Push-ups", "description": "Do 10 of each exercise, twice through.", "time_estimate": "5 min", "reward_amount": 18},
        {"title": "Walking Meditation", "description": "Walk slowly for 5 minutes, focusing on each step.", "time_estimate": "5 min", "reward_amount": 12},
        {"title": "Quick HIIT", "description": "30 seconds jumping jacks, 30 seconds rest. Repeat 5 times.", "time_estimate": "5 min", "reward_amount": 18},
        {"title": "Plank Series", "description": "30 sec regular plank, 30 sec each side plank. Repeat twice.", "time_estimate": "4 min", "reward_amount": 15},
        {"title": "Leg Workout", "description": "15 squats, 10 lunges each leg, 20 calf raises.", "time_estimate": "5 min", "reward_amount": 18},
        {"title": "Arm Toning", "description": "15 push-ups, 15 dips, 30 arm circles.", "time_estimate": "5 min", "reward_amount": 15},
        {"title": "Core Blast", "description": "20 crunches, 20 bicycle kicks, 30 second plank.", "time_estimate": "4 min", "reward_amount": 15},
        {"title": "Office Workout", "description": "Chair squats, desk push-ups, and standing leg raises. 10 each.", "time_estimate": "5 min", "reward_amount": 15},
        {"title": "Jogging in Place", "description": "Jog in place for 5 minutes. Mix in some high knees!", "time_estimate": "5 min", "reward_amount": 15},
        {"title": "Pilates Core Series", "description": "Single leg stretch, double leg stretch, scissors. 10 each.", "time_estimate": "5 min", "reward_amount": 15},
        {"title": "Active Recovery Stretch", "description": "Gentle stretching for all major muscle groups.", "time_estimate": "5 min", "reward_amount": 12},
        {"title": "Balance Training", "description": "Single leg stands, heel-to-toe walk, one-leg squats. 1 min each.", "time_estimate": "5 min", "reward_amount": 15},
        {"title": "Tabata Round", "description": "20 sec squats, 10 sec rest. 8 rounds total.", "time_estimate": "4 min", "reward_amount": 15},
        {"title": "Morning Wake-up Routine", "description": "Stretch, 10 jumping jacks, 10 squats, 5 push-ups.", "time_estimate": "5 min", "reward_amount": 15},
        {"title": "Lower Body Burn", "description": "20 squats, 20 lunges, 20 glute bridges.", "time_estimate": "5 min", "reward_amount": 18},
        {"title": "Upper Body Push", "description": "15 push-ups, 15 diamond push-ups, 30 sec plank.", "time_estimate": "5 min", "reward_amount": 15},
        {"title": "Hip Mobility Routine", "description": "Hip circles, pigeon stretch, butterfly. 1 min each.", "time_estimate": "5 min", "reward_amount": 12},
        {"title": "Cardio Burst", "description": "1 min each: jumping jacks, high knees, butt kicks, burpees.", "time_estimate": "4 min", "reward_amount": 15},
        {"title": "Desk Jockey Relief", "description": "Chest opener, hip flexor stretch, seated twist. 1 min each.", "time_estimate": "5 min", "reward_amount": 12},
        {"title": "Strength Circuit", "description": "10 squats, 10 push-ups, 10 lunges. Three rounds.", "time_estimate": "5 min", "reward_amount": 18},
        {"title": "Flexibility Focus", "description": "Hold each stretch for 45 seconds: hamstrings, quads, shoulders, back.", "time_estimate": "4 min", "reward_amount": 12},
        {"title": "Quick Outdoor Walk", "description": "Step outside and walk briskly for 5 minutes.", "time_estimate": "5 min", "reward_amount": 15},
        {"title": "Bodyweight Pyramid", "description": "5-4-3-2-1 squats and push-ups. Descending ladder!", "time_estimate": "4 min", "reward_amount": 15},
        {"title": "Standing Ab Workout", "description": "Standing crunches, side bends, knee raises. 15 each.", "time_estimate": "4 min", "reward_amount": 12},
        {"title": "Glute Activation", "description": "Glute bridges, donkey kicks, fire hydrants. 12 each.", "time_estimate": "5 min", "reward_amount": 15},
        {"title": "Shoulder Mobility", "description": "Arm circles, shoulder shrugs, wall slides. 1 min each.", "time_estimate": "4 min", "reward_amount": 10},
        {"title": "Quick EMOM", "description": "Every minute: 10 squats. Rest remainder. 5 minutes.", "time_estimate": "5 min", "reward_amount": 15},
        {"title": "Functional Movement Flow", "description": "Squat to stand, lunge with twist, inchworm. 5 rounds.", "time_estimate": "5 min", "reward_amount": 15},
        {"title": "Core and Cardio Combo", "description": "30 sec plank, 30 sec jumping jacks. 4 rounds.", "time_estimate": "4 min", "reward_amount": 15},
        {"title": "Posture Reset Routine", "description": "Chin tucks, chest stretch, cat-cow stretches. 1 min each.", "time_estimate": "4 min", "reward_amount": 12},
        {"title": "Athletic Movement Prep", "description": "Leg swings, arm circles, light jog, high knees.", "time_estimate": "5 min", "reward_amount": 12},
        {"title": "Stress Relief Stretches", "description": "Neck rolls, shoulder release, hip opener, forward fold.", "time_estimate": "5 min", "reward_amount": 12},
        {"title": "Quick Abs Circuit", "description": "Plank, side plank left, side plank right. 40 seconds each.", "time_estimate": "3 min", "reward_amount": 12},
        {"title": "Desk Yoga Break", "description": "Seated twist, neck stretch, wrist circles, seated cat-cow.", "time_estimate": "4 min", "reward_amount": 10},
        {"title": "Lower Back Relief", "description": "Cat-cow, child's pose, knee-to-chest. 1 min each.", "time_estimate": "4 min", "reward_amount": 12},
        {"title": "Morning Energizer", "description": "Jumping jacks, arm swings, squats, torso twists. 30 sec each.", "time_estimate": "3 min", "reward_amount": 10},
        {"title": "Beginner Burpee Practice", "description": "5 modified burpees (no jump, step back). Focus on form.", "time_estimate": "3 min", "reward_amount": 12},
        {"title": "Standing Full Body Stretch", "description": "Reach up, side bend, forward fold, quad stretch.", "time_estimate": "4 min", "reward_amount": 10},
        {"title": "Quick Cardio Dance", "description": "Put on an upbeat song and move! No rules, just fun.", "time_estimate": "4 min", "reward_amount": 12},
        {"title": "Wall Workout", "description": "Wall push-ups, wall sit, calf raises against wall.", "time_estimate": "5 min", "reward_amount": 15},
        {"title": "Park Bench Workout", "description": "Step-ups, incline push-ups, seated leg raises.", "time_estimate": "5 min", "reward_amount": 15},
        {"title": "Hotel Room Fitness", "description": "Jumping jacks, towel rows, suitcase squats.", "time_estimate": "5 min", "reward_amount": 15},

        # 10+ min tasks (30 tasks)
        {"title": "30-Minute Walk", "description": "Go for a refreshing 30-minute walk outside.", "time_estimate": "30 min", "reward_amount": 25},
        {"title": "Full Body Workout", "description": "Complete workout: warm-up, strength, cardio, cool-down.", "time_estimate": "20 min", "reward_amount": 25},
        {"title": "Yoga Session", "description": "Follow a 15-minute yoga video or do your own flow.", "time_estimate": "15 min", "reward_amount": 22},
        {"title": "Run or Jog", "description": "Go for a 15-minute run or jog at your own pace.", "time_estimate": "15 min", "reward_amount": 22},
        {"title": "Bike Ride", "description": "Take your bike out for a 20-minute ride.", "time_estimate": "20 min", "reward_amount": 25},
        {"title": "Swimming", "description": "Swim for 20 minutes if you have access to a pool.", "time_estimate": "20 min", "reward_amount": 25},
        {"title": "HIIT Workout", "description": "20 minutes of high-intensity interval training.", "time_estimate": "20 min", "reward_amount": 25},
        {"title": "Strength Training", "description": "Do a 20-minute strength workout with weights or bodyweight.", "time_estimate": "20 min", "reward_amount": 25},
        {"title": "Pilates Session", "description": "Complete a 15-minute Pilates routine.", "time_estimate": "15 min", "reward_amount": 22},
        {"title": "Active Stretching Routine", "description": "15 minutes of dynamic and static stretching.", "time_estimate": "15 min", "reward_amount": 20},
        {"title": "Dance Workout", "description": "Follow a 15-minute dance fitness video.", "time_estimate": "15 min", "reward_amount": 22},
        {"title": "Boxing Workout", "description": "Shadow boxing routine with footwork. 15 minutes.", "time_estimate": "15 min", "reward_amount": 22},
        {"title": "Stairs Challenge", "description": "Walk or run stairs for 10 minutes straight.", "time_estimate": "10 min", "reward_amount": 20},
        {"title": "Jump Rope Session", "description": "Jump rope for 10 minutes with short breaks.", "time_estimate": "10 min", "reward_amount": 20},
        {"title": "Mobility Work", "description": "15 minutes focusing on joint mobility and flexibility.", "time_estimate": "15 min", "reward_amount": 20},
        {"title": "Nature Hike", "description": "Take a 30-minute hike in nature.", "time_estimate": "30 min", "reward_amount": 25},
        {"title": "Sports Activity", "description": "Play a sport for 20 minutes: basketball, tennis, soccer.", "time_estimate": "20 min", "reward_amount": 25},
        {"title": "Circuit Training", "description": "3 rounds of 5 exercises. 1 minute each, 30 sec rest.", "time_estimate": "20 min", "reward_amount": 25},
        {"title": "Yin Yoga", "description": "Slow, deep stretches held for 2-3 minutes each.", "time_estimate": "20 min", "reward_amount": 22},
        {"title": "Morning Workout Routine", "description": "Complete your morning exercise routine.", "time_estimate": "20 min", "reward_amount": 25},
        {"title": "Evening Wind-Down Stretches", "description": "Gentle 15-minute stretching before bed.", "time_estimate": "15 min", "reward_amount": 20},
        {"title": "Resistance Band Workout", "description": "Full body resistance band exercises for 15 minutes.", "time_estimate": "15 min", "reward_amount": 22},
        {"title": "Core Strengthening", "description": "15-minute focused core workout.", "time_estimate": "15 min", "reward_amount": 22},
        {"title": "Upper Body Focus", "description": "20-minute upper body strength workout.", "time_estimate": "20 min", "reward_amount": 25},
        {"title": "Lower Body Focus", "description": "20-minute lower body strength workout.", "time_estimate": "20 min", "reward_amount": 25},
        {"title": "Cardio Mix", "description": "15 minutes alternating between different cardio exercises.", "time_estimate": "15 min", "reward_amount": 22},
        {"title": "Foam Rolling", "description": "10 minutes of self-massage with foam roller.", "time_estimate": "10 min", "reward_amount": 18},
        {"title": "Balance and Stability", "description": "15 minutes of balance exercises.", "time_estimate": "15 min", "reward_amount": 20},
        {"title": "Functional Fitness", "description": "20 minutes of everyday movement patterns.", "time_estimate": "20 min", "reward_amount": 25},
        {"title": "Outdoor Workout", "description": "Take your workout outside for 20 minutes.", "time_estimate": "20 min", "reward_amount": 25},
    ],
    
    "focus": [
        # Quick 1-min tasks
        {"title": "One Deep Breath", "description": "Take one very deep breath. Inhale for 4 seconds, hold for 4, exhale for 4.", "time_estimate": "1 min", "reward_amount": 3},
        {"title": "Close Unnecessary Tabs", "description": "Close all browser tabs you don't need right now. Digital declutter!", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Phone on Silent", "description": "Put your phone on silent and face-down for the next 30 minutes.", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Mindful Minute", "description": "Close your eyes and focus only on your breathing for 60 seconds.", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Positive Affirmation", "description": "Say out loud: 'I am focused and productive.' Believe it!", "time_estimate": "1 min", "reward_amount": 3},
        {"title": "Morning Intention", "description": "Set one clear intention for how you want to feel today.", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Clear Visual Clutter", "description": "Remove 3 items from your immediate view that distract you.", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Power Pose", "description": "Stand in a confident pose for 60 seconds. Feel powerful!", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Name Your Distraction", "description": "Identify what's distracting you most right now. Awareness helps!", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Quick Desk Tidy", "description": "Quickly organize items within arm's reach.", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Notification Check", "description": "Turn off notifications for the next hour.", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Close Social Media", "description": "Close all social media apps and tabs right now.", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Water Break", "description": "Drink water and refresh your mind.", "time_estimate": "1 min", "reward_amount": 3},
        {"title": "Eye Reset", "description": "Look away from screen, focus on something distant for 30 seconds.", "time_estimate": "1 min", "reward_amount": 3},
        {"title": "Mental Reset", "description": "Close eyes, count to 10 slowly, open refreshed.", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Priority Check", "description": "Remind yourself what your #1 priority is today.", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Quick Win Identification", "description": "Identify one small task you can finish in the next 5 minutes.", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Posture Reset", "description": "Sit up straight, align your spine, feel more alert.", "time_estimate": "1 min", "reward_amount": 3},
        {"title": "Aromatherapy Pause", "description": "Smell something refreshing: coffee, mint, citrus.", "time_estimate": "1 min", "reward_amount": 3},
        {"title": "Mini Stretch", "description": "Stretch your neck and shoulders to release tension.", "time_estimate": "1 min", "reward_amount": 3},
        
        # 2-3 min tasks
        {"title": "Clear Your Desk", "description": "Take 2 minutes to organize your immediate workspace. Clear space, clear mind.", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Set Today's Priority", "description": "Write down the ONE most important thing you need to do today.", "time_estimate": "2 min", "reward_amount": 10},
        {"title": "Brain Dump", "description": "Write down everything on your mind for 3 minutes. Get it out of your head!", "time_estimate": "3 min", "reward_amount": 10},
        {"title": "Review Your Goals", "description": "Read through your goals. Remind yourself why you're working hard.", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Eliminate One Distraction", "description": "Identify and remove one thing that's distracting you right now.", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Two-Minute Rule", "description": "Do one task that takes less than 2 minutes. Just get it done!", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Plan Tomorrow", "description": "Write down 3 things you'll accomplish tomorrow.", "time_estimate": "3 min", "reward_amount": 10},
        {"title": "Visualize Success", "description": "Close your eyes and visualize completing your most important task.", "time_estimate": "2 min", "reward_amount": 5},
        {"title": "Break a Task Down", "description": "Take a big task and break it into 3 smaller steps.", "time_estimate": "3 min", "reward_amount": 10},
        {"title": "Workspace Reset", "description": "Reset your workspace to how it looks when you're most productive.", "time_estimate": "3 min", "reward_amount": 8},
        {"title": "Time Block", "description": "Block out 1 hour on your calendar for deep work today.", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Say No to One Thing", "description": "Decline or postpone one commitment that's not essential.", "time_estimate": "2 min", "reward_amount": 10},
        {"title": "Progress Check", "description": "Review what you've accomplished so far today. Celebrate wins!", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Gratitude Pause", "description": "Think of one thing about your work that you're grateful for.", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Energy Assessment", "description": "Rate your energy 1-10. What would increase it by 1 point?", "time_estimate": "2 min", "reward_amount": 5},
        {"title": "Top 3 for Tomorrow", "description": "Write your top 3 priorities for tomorrow before leaving today.", "time_estimate": "3 min", "reward_amount": 10},
        {"title": "Capture Ideas", "description": "Write down any ideas floating in your head so you can focus.", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Define Done", "description": "For your current task, write what 'done' looks like.", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Minimize Windows", "description": "Close or minimize all windows except what you need right now.", "time_estimate": "2 min", "reward_amount": 5},
        {"title": "Set a Timer", "description": "Set a timer for 25 minutes and commit to focused work.", "time_estimate": "2 min", "reward_amount": 5},
        {"title": "Identify Blockers", "description": "What's blocking you from progress? Write it down.", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Create a To-Don't List", "description": "List 3 things you won't do today to protect your focus.", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Quick Email Scan", "description": "Scan emails for urgent items only. Defer the rest.", "time_estimate": "3 min", "reward_amount": 8},
        {"title": "Meeting Audit", "description": "Cancel or shorten one unnecessary meeting this week.", "time_estimate": "3 min", "reward_amount": 10},
        {"title": "Focus Music Setup", "description": "Put on focus-friendly music or white noise.", "time_estimate": "2 min", "reward_amount": 5},
        
        # 5 min tasks
        {"title": "5-Minute Focus Sprint", "description": "Work on your most important task for exactly 5 minutes. No distractions.", "time_estimate": "5 min", "reward_amount": 15},
        {"title": "Inbox Zero Push", "description": "Process 5 emails right now. Reply, delete, or archive.", "time_estimate": "5 min", "reward_amount": 12},
        {"title": "Learn One Thing", "description": "Read one article or watch one video related to your work.", "time_estimate": "5 min", "reward_amount": 12},
        {"title": "Weekly Review Prep", "description": "Note your wins, challenges, and learnings from this week.", "time_estimate": "5 min", "reward_amount": 12},
        {"title": "Tomorrow's Plan", "description": "Plan out tomorrow hour by hour.", "time_estimate": "5 min", "reward_amount": 12},
        {"title": "Organize One Folder", "description": "Organize digital or physical files in one folder.", "time_estimate": "5 min", "reward_amount": 10},
        {"title": "Clear 5 To-Dos", "description": "Complete or delete 5 small items from your to-do list.", "time_estimate": "5 min", "reward_amount": 15},
        {"title": "Mind Mapping", "description": "Create a mind map for a project or problem you're working on.", "time_estimate": "5 min", "reward_amount": 12},
        {"title": "Prioritization Exercise", "description": "Rank your tasks by importance and urgency.", "time_estimate": "5 min", "reward_amount": 12},
        {"title": "Digital Cleanup", "description": "Delete old files or apps you no longer need.", "time_estimate": "5 min", "reward_amount": 10},
        {"title": "Focus Ritual Creation", "description": "Design a 2-minute ritual to start your focus sessions.", "time_estimate": "5 min", "reward_amount": 12},
        {"title": "Environment Optimization", "description": "Make 3 changes to your workspace to boost focus.", "time_estimate": "5 min", "reward_amount": 12},
        {"title": "Reflection Journal", "description": "Write about what's working and not working in your productivity.", "time_estimate": "5 min", "reward_amount": 12},
        {"title": "Tool Audit", "description": "List the tools you use for work. Any redundant ones?", "time_estimate": "5 min", "reward_amount": 10},
        {"title": "Habit Tracking Setup", "description": "Set up tracking for one focus habit you want to build.", "time_estimate": "5 min", "reward_amount": 12},
        
        # 10+ min tasks
        {"title": "Single-Task Challenge", "description": "Pick one task and do ONLY that for the next 10 minutes.", "time_estimate": "10 min", "reward_amount": 20},
        {"title": "Pomodoro Start", "description": "Set a timer for 25 minutes and focus on one task until it rings.", "time_estimate": "25 min", "reward_amount": 25},
        {"title": "Deep Work Session", "description": "30 minutes of uninterrupted, focused work on your most important task.", "time_estimate": "30 min", "reward_amount": 25},
        {"title": "Weekly Planning", "description": "Plan your entire week: priorities, meetings, focus time.", "time_estimate": "20 min", "reward_amount": 25},
        {"title": "Monthly Review", "description": "Review the past month: wins, lessons, goals for next month.", "time_estimate": "20 min", "reward_amount": 25},
        {"title": "Project Planning", "description": "Break down a project into tasks and milestones.", "time_estimate": "20 min", "reward_amount": 25},
        {"title": "Learning Block", "description": "Dedicate 20 minutes to learning something new for your work.", "time_estimate": "20 min", "reward_amount": 22},
        {"title": "Creative Thinking Time", "description": "15 minutes of unstructured thinking about a challenge.", "time_estimate": "15 min", "reward_amount": 20},
        {"title": "Email Batch Processing", "description": "Process all emails in one 20-minute block.", "time_estimate": "20 min", "reward_amount": 22},
        {"title": "Task Batching", "description": "Group similar tasks and complete them in one session.", "time_estimate": "20 min", "reward_amount": 22},
        {"title": "Focus Environment Day", "description": "Spend 15 minutes optimizing your workspace for focus.", "time_estimate": "15 min", "reward_amount": 20},
        {"title": "Double Pomodoro", "description": "Two 25-minute focus sessions with a 5-minute break between.", "time_estimate": "55 min", "reward_amount": 25},
        {"title": "Morning Routine Optimization", "description": "Design your ideal morning routine for productivity.", "time_estimate": "15 min", "reward_amount": 20},
        {"title": "Evening Shutdown Ritual", "description": "Create a ritual to end your workday and transition.", "time_estimate": "15 min", "reward_amount": 20},
        {"title": "Focus Audit", "description": "Analyze where your focus goes during a typical day.", "time_estimate": "15 min", "reward_amount": 20},
    ],
    
    "business": [
        # Quick 1-3 min tasks
        {"title": "Reply to One Email", "description": "Answer one important email you've been putting off.", "time_estimate": "3 min", "reward_amount": 10},
        {"title": "Network Outreach", "description": "Send a LinkedIn message or email to one professional contact.", "time_estimate": "3 min", "reward_amount": 12},
        {"title": "Follow Up", "description": "Follow up with someone you met or contacted recently.", "time_estimate": "3 min", "reward_amount": 10},
        {"title": "Review Your Goals", "description": "Look at your business/career goals. Are you on track?", "time_estimate": "3 min", "reward_amount": 8},
        {"title": "Send a Thank You", "description": "Send a thank you message to someone who helped you recently.", "time_estimate": "3 min", "reward_amount": 10},
        {"title": "Schedule a Meeting", "description": "Reach out to schedule a meeting with someone valuable.", "time_estimate": "3 min", "reward_amount": 10},
        {"title": "Pitch Practice", "description": "Practice your elevator pitch out loud for 2 minutes.", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Process Improvement", "description": "Identify one thing in your work process you could do better.", "time_estimate": "3 min", "reward_amount": 10},
        {"title": "Delegate Something", "description": "Identify one task you could delegate or automate.", "time_estimate": "3 min", "reward_amount": 10},
        {"title": "Celebrate a Win", "description": "Write down one recent business win, big or small.", "time_estimate": "2 min", "reward_amount": 5},
        {"title": "Ask for Feedback", "description": "Ask one colleague or customer for feedback on your work.", "time_estimate": "3 min", "reward_amount": 12},
        {"title": "Set a Deadline", "description": "Set a specific deadline for one task you've been avoiding.", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Review Metrics", "description": "Check one key metric for your business or work performance.", "time_estimate": "3 min", "reward_amount": 10},
        {"title": "LinkedIn Post Comment", "description": "Leave a thoughtful comment on an industry post.", "time_estimate": "3 min", "reward_amount": 8},
        {"title": "Update Bio", "description": "Update your bio on one platform.", "time_estimate": "3 min", "reward_amount": 8},
        {"title": "Clear One Invoice", "description": "Send or process one invoice.", "time_estimate": "3 min", "reward_amount": 10},
        {"title": "Meeting Prep", "description": "Prepare one key point for your next meeting.", "time_estimate": "3 min", "reward_amount": 8},
        {"title": "KPI Check", "description": "Review one key performance indicator.", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Industry News Scan", "description": "Scan headlines for industry news.", "time_estimate": "3 min", "reward_amount": 5},
        {"title": "Contact Update", "description": "Update contact info for one important connection.", "time_estimate": "2 min", "reward_amount": 5},
        
        # 5 min tasks
        {"title": "Learn Industry News", "description": "Read one article about your industry. Stay informed!", "time_estimate": "5 min", "reward_amount": 10},
        {"title": "Update Your LinkedIn", "description": "Add one new skill or update one section of your LinkedIn profile.", "time_estimate": "5 min", "reward_amount": 15},
        {"title": "Brainstorm Ideas", "description": "Write down 5 ideas for your business or career growth.", "time_estimate": "5 min", "reward_amount": 15},
        {"title": "Learn a Skill", "description": "Watch a 5-minute tutorial on a skill you want to improve.", "time_estimate": "5 min", "reward_amount": 12},
        {"title": "Organize Files", "description": "Organize one folder on your computer. Delete what you don't need.", "time_estimate": "5 min", "reward_amount": 10},
        {"title": "Review Finances", "description": "Spend 5 minutes reviewing your business or personal finances.", "time_estimate": "5 min", "reward_amount": 12},
        {"title": "Competitor Check", "description": "Spend 5 minutes looking at what your competitors are doing.", "time_estimate": "5 min", "reward_amount": 10},
        {"title": "Update Resume", "description": "Add one recent accomplishment to your resume.", "time_estimate": "5 min", "reward_amount": 15},
        {"title": "Professional Post", "description": "Share something valuable on LinkedIn or your professional platform.", "time_estimate": "5 min", "reward_amount": 12},
        {"title": "Customer Outreach", "description": "Reach out to one customer or potential customer.", "time_estimate": "5 min", "reward_amount": 15},
        {"title": "Mentor Moment", "description": "Share one piece of advice with someone less experienced.", "time_estimate": "5 min", "reward_amount": 12},
        {"title": "Plan Next Week", "description": "Write down your top 3 priorities for next week.", "time_estimate": "5 min", "reward_amount": 12},
        {"title": "Revenue Brainstorm", "description": "Think of 3 ways to increase revenue in your work.", "time_estimate": "5 min", "reward_amount": 15},
        {"title": "Cost Reduction Idea", "description": "Identify one cost you could reduce.", "time_estimate": "5 min", "reward_amount": 12},
        {"title": "Client Follow-Up", "description": "Send a check-in message to a past client.", "time_estimate": "5 min", "reward_amount": 12},
        {"title": "Industry Report Scan", "description": "Review highlights from a recent industry report.", "time_estimate": "5 min", "reward_amount": 10},
        {"title": "Skill Gap Identification", "description": "Identify one skill that would help your career.", "time_estimate": "5 min", "reward_amount": 10},
        {"title": "Success Story Collection", "description": "Document one success story or case study.", "time_estimate": "5 min", "reward_amount": 12},
        {"title": "Referral Ask", "description": "Ask one satisfied client for a referral or testimonial.", "time_estimate": "5 min", "reward_amount": 15},
        {"title": "Process Documentation", "description": "Document one process you do regularly.", "time_estimate": "5 min", "reward_amount": 12},
        
        # 10-20 min tasks
        {"title": "Weekly Business Review", "description": "Review your business metrics and goals for the week.", "time_estimate": "15 min", "reward_amount": 22},
        {"title": "Strategy Session", "description": "Spend 15 minutes thinking strategically about your business.", "time_estimate": "15 min", "reward_amount": 22},
        {"title": "Networking Research", "description": "Research 5 people you want to connect with.", "time_estimate": "15 min", "reward_amount": 20},
        {"title": "Proposal Draft", "description": "Draft the outline of a proposal or pitch.", "time_estimate": "15 min", "reward_amount": 22},
        {"title": "Financial Planning", "description": "Review and plan your finances for the next month.", "time_estimate": "20 min", "reward_amount": 25},
        {"title": "Market Research", "description": "Research your market or target audience for 15 minutes.", "time_estimate": "15 min", "reward_amount": 20},
        {"title": "Content Creation", "description": "Write a short article or post for your professional audience.", "time_estimate": "20 min", "reward_amount": 25},
        {"title": "Client Meeting Prep", "description": "Prepare thoroughly for an upcoming client meeting.", "time_estimate": "15 min", "reward_amount": 22},
        {"title": "Sales Pipeline Review", "description": "Review and update your sales pipeline.", "time_estimate": "15 min", "reward_amount": 22},
        {"title": "Partnership Exploration", "description": "Research potential partnership opportunities.", "time_estimate": "15 min", "reward_amount": 20},
        {"title": "Business Model Review", "description": "Evaluate your current business model.", "time_estimate": "20 min", "reward_amount": 25},
        {"title": "Quarterly Goals Setting", "description": "Set your goals for the next quarter.", "time_estimate": "20 min", "reward_amount": 25},
        {"title": "Pricing Strategy Review", "description": "Review and optimize your pricing.", "time_estimate": "15 min", "reward_amount": 22},
        {"title": "Customer Journey Mapping", "description": "Map out your customer's experience.", "time_estimate": "20 min", "reward_amount": 25},
        {"title": "Competitive Analysis", "description": "Deep dive into one competitor's strategy.", "time_estimate": "20 min", "reward_amount": 25},
        
        # 30+ min tasks
        {"title": "Monthly Business Review", "description": "Comprehensive review of your business performance.", "time_estimate": "30 min", "reward_amount": 25},
        {"title": "Strategic Planning Session", "description": "Deep strategic thinking about your business direction.", "time_estimate": "30 min", "reward_amount": 25},
        {"title": "Networking Event", "description": "Attend a virtual or in-person networking event.", "time_estimate": "60 min", "reward_amount": 25},
        {"title": "Skills Training", "description": "Complete a training module or course section.", "time_estimate": "30 min", "reward_amount": 25},
        {"title": "Business Plan Update", "description": "Update your business plan with recent learnings.", "time_estimate": "30 min", "reward_amount": 25},
        {"title": "Annual Review Prep", "description": "Prepare materials for annual review or planning.", "time_estimate": "30 min", "reward_amount": 25},
    ],
    
    "relationships": [
        # Quick 1-3 min tasks
        {"title": "Send a Kind Text", "description": "Text a friend or family member something nice right now.", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Schedule a Call", "description": "Schedule a phone or video call with someone you miss.", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Compliment Someone", "description": "Give a genuine compliment to someone today.", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Offer Help", "description": "Offer to help someone with something they're working on.", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Put Phone Away", "description": "Put your phone away during your next conversation. Be present.", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Say I Love You", "description": "Tell someone important that you love them.", "time_estimate": "1 min", "reward_amount": 8},
        {"title": "Photo Memory", "description": "Send someone a photo that reminds you of a good time together.", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Verbal Appreciation", "description": "Tell someone specifically what you admire about them.", "time_estimate": "2 min", "reward_amount": 10},
        {"title": "Make Plans", "description": "Don't just say 'let's hang out' - set an actual date and time.", "time_estimate": "3 min", "reward_amount": 10},
        {"title": "Good Morning Text", "description": "Send a good morning message to someone you care about.", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Thinking of You", "description": "Let someone know you're thinking about them.", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Ask How They're Doing", "description": "Check in on someone with a quick message.", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Share Something Funny", "description": "Share a meme or joke with someone who would appreciate it.", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Voice Note", "description": "Send a voice message instead of a text. It's more personal!", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Save a Date", "description": "Mark someone's birthday or important date in your calendar.", "time_estimate": "2 min", "reward_amount": 5},
        {"title": "Recommend Something", "description": "Recommend a book, show, or song you think they'd love.", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Express Interest", "description": "Ask someone about their hobby or interest.", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Support Message", "description": "Send an encouraging message to someone going through a tough time.", "time_estimate": "2 min", "reward_amount": 10},
        {"title": "Celebrate Their Win", "description": "Congratulate someone on a recent achievement.", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Inside Joke Moment", "description": "Reference an inside joke with a close friend.", "time_estimate": "1 min", "reward_amount": 5},
        
        # 3-5 min tasks
        {"title": "Express Gratitude", "description": "Tell someone why you appreciate them. Be specific!", "time_estimate": "3 min", "reward_amount": 12},
        {"title": "Forgiveness Practice", "description": "Think of someone you need to forgive. Take a step toward letting go.", "time_estimate": "3 min", "reward_amount": 10},
        {"title": "Ask About Their Day", "description": "Ask someone how their day is going and really listen to the answer.", "time_estimate": "3 min", "reward_amount": 8},
        {"title": "Share a Memory", "description": "Share a happy memory with someone who was there.", "time_estimate": "3 min", "reward_amount": 10},
        {"title": "Reconnect", "description": "Reach out to someone you haven't talked to in a while.", "time_estimate": "3 min", "reward_amount": 12},
        {"title": "Check In", "description": "Check in on someone who might be going through a hard time.", "time_estimate": "3 min", "reward_amount": 12},
        {"title": "Apologize", "description": "If you owe someone an apology, now's the time. Be sincere.", "time_estimate": "3 min", "reward_amount": 15},
        {"title": "Plan a Date", "description": "Plan a date or hangout with your partner, friend, or family member.", "time_estimate": "5 min", "reward_amount": 12},
        {"title": "Listen Fully", "description": "Have a conversation where you only listen. Don't think about your response.", "time_estimate": "5 min", "reward_amount": 15},
        {"title": "Write a Note", "description": "Write a short handwritten note to someone you care about.", "time_estimate": "5 min", "reward_amount": 15},
        {"title": "Small Gesture", "description": "Do a small act of kindness for someone. Make their day!", "time_estimate": "5 min", "reward_amount": 15},
        {"title": "Boundary Setting", "description": "Set one healthy boundary in a relationship that needs it.", "time_estimate": "5 min", "reward_amount": 15},
        {"title": "Family Call", "description": "Call a family member you haven't spoken to recently.", "time_estimate": "5 min", "reward_amount": 15},
        {"title": "Be Vulnerable", "description": "Share something real about how you're feeling with someone you trust.", "time_estimate": "5 min", "reward_amount": 15},
        {"title": "Random Act of Kindness", "description": "Do something kind for a stranger today.", "time_estimate": "5 min", "reward_amount": 12},
        {"title": "Conflict Resolution", "description": "Take a step toward resolving a conflict with someone.", "time_estimate": "5 min", "reward_amount": 18},
        {"title": "Active Listening Practice", "description": "Practice asking follow-up questions in your next conversation.", "time_estimate": "5 min", "reward_amount": 12},
        {"title": "Appreciation Letter", "description": "Start writing a letter of appreciation to someone special.", "time_estimate": "5 min", "reward_amount": 15},
        {"title": "Future Plans", "description": "Discuss future plans or dreams with someone close to you.", "time_estimate": "5 min", "reward_amount": 12},
        {"title": "Memory Lane", "description": "Look through old photos with someone and reminisce.", "time_estimate": "5 min", "reward_amount": 12},
        
        # 10+ min tasks
        {"title": "Quality Time", "description": "Spend 10 minutes of undivided attention with someone.", "time_estimate": "10 min", "reward_amount": 20},
        {"title": "Deep Conversation", "description": "Have a meaningful conversation about life, dreams, or feelings.", "time_estimate": "15 min", "reward_amount": 22},
        {"title": "Phone Call", "description": "Call someone instead of texting. Real connection!", "time_estimate": "15 min", "reward_amount": 20},
        {"title": "Video Chat", "description": "Have a video call with someone you can't see in person.", "time_estimate": "20 min", "reward_amount": 22},
        {"title": "Help with a Project", "description": "Help someone with a task or project they're working on.", "time_estimate": "20 min", "reward_amount": 22},
        {"title": "Letter Writing", "description": "Write a heartfelt letter to someone important in your life.", "time_estimate": "20 min", "reward_amount": 25},
        {"title": "Relationship Reflection", "description": "Reflect on your key relationships. How can you nurture them?", "time_estimate": "15 min", "reward_amount": 20},
        {"title": "Cook for Someone", "description": "Prepare a meal or snack for someone you care about.", "time_estimate": "30 min", "reward_amount": 25},
        {"title": "Teach Something", "description": "Share a skill or knowledge with someone who wants to learn.", "time_estimate": "20 min", "reward_amount": 22},
        {"title": "Game Time", "description": "Play a game with friends or family.", "time_estimate": "30 min", "reward_amount": 25},
        {"title": "Movie Night Planning", "description": "Plan and organize a movie night with loved ones.", "time_estimate": "15 min", "reward_amount": 20},
        {"title": "Photo Album Creation", "description": "Create a small digital album of memories to share.", "time_estimate": "20 min", "reward_amount": 22},
        {"title": "Surprise Planning", "description": "Plan a small surprise for someone you care about.", "time_estimate": "15 min", "reward_amount": 22},
        {"title": "Support Session", "description": "Be there for someone who needs to talk.", "time_estimate": "20 min", "reward_amount": 25},
        {"title": "Couple's Check-In", "description": "Have a relationship check-in conversation with your partner.", "time_estimate": "20 min", "reward_amount": 25},
    ],
    
    "spiritual": [
        # Quick 1-2 min tasks
        {"title": "Mindful Breathing", "description": "Take 10 deep, slow breaths. Focus only on your breathing.", "time_estimate": "2 min", "reward_amount": 5},
        {"title": "Meditation Minute", "description": "Close your eyes and sit in silence for 60 seconds.", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Affirmation", "description": "Repeat a positive affirmation 5 times. Believe it.", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Present Moment", "description": "Notice 5 things you can see, 4 you can hear, 3 you can feel.", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Send Love", "description": "Think of 3 people and mentally send them love and good wishes.", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Digital Sunset", "description": "Turn off screens for the next 30 minutes. Be present.", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Let Go", "description": "Identify one worry. Visualize releasing it like a balloon.", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Loving Kindness", "description": "Repeat: 'May I be happy. May I be healthy. May I be at peace.'", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Earth Connection", "description": "Stand barefoot on grass or earth for 2 minutes if possible.", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Self-Compassion", "description": "Say to yourself: 'I am doing my best, and that is enough.'", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Set an Intention", "description": "Set one intention for how you want to show up today.", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Pause and Notice", "description": "Stop everything and notice how you feel right now.", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Sky Gazing", "description": "Look at the sky for 2 minutes. Notice clouds, colors, movement.", "time_estimate": "2 min", "reward_amount": 5},
        {"title": "Hand on Heart", "description": "Place hand on heart, breathe deeply, feel your heartbeat.", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Body Awareness", "description": "Notice where you hold tension in your body right now.", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Smile Meditation", "description": "Close eyes, breathe, and bring a gentle smile to your face.", "time_estimate": "2 min", "reward_amount": 5},
        {"title": "Thank the Day", "description": "Thank the day for whatever it brought, good or challenging.", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Candle Gazing", "description": "Light a candle and gaze softly at the flame for 2 minutes.", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Sound Awareness", "description": "Close eyes and notice every sound around you for 1 minute.", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Breath Counting", "description": "Count your breaths up to 10, then start over. Repeat 3 times.", "time_estimate": "2 min", "reward_amount": 5},
        
        # 3-5 min tasks
        {"title": "Gratitude List", "description": "Write down 3 things you're grateful for right now.", "time_estimate": "3 min", "reward_amount": 10},
        {"title": "Nature Moment", "description": "Step outside and observe nature for 2 minutes. No phone.", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Body Scan", "description": "Close your eyes and notice how each part of your body feels.", "time_estimate": "3 min", "reward_amount": 8},
        {"title": "Forgiveness", "description": "Think of someone you need to forgive. Send them love mentally.", "time_estimate": "3 min", "reward_amount": 10},
        {"title": "Read Something Inspiring", "description": "Read a quote, verse, or passage that inspires you.", "time_estimate": "3 min", "reward_amount": 8},
        {"title": "Pray or Reflect", "description": "Spend 3 minutes in prayer or quiet reflection.", "time_estimate": "3 min", "reward_amount": 10},
        {"title": "Connect with Silence", "description": "Sit in complete silence for 3 minutes. No music, no talking.", "time_estimate": "3 min", "reward_amount": 10},
        {"title": "Count Blessings", "description": "Count 10 blessings in your life, big or small.", "time_estimate": "3 min", "reward_amount": 10},
        {"title": "Mindful Walk", "description": "Take a short walk focusing only on each step.", "time_estimate": "5 min", "reward_amount": 12},
        {"title": "Sunrise/Sunset", "description": "Watch the sunrise or sunset. Just observe.", "time_estimate": "5 min", "reward_amount": 12},
        {"title": "Journaling", "description": "Write freely about your thoughts and feelings for 5 minutes.", "time_estimate": "5 min", "reward_amount": 12},
        {"title": "Declutter Mind", "description": "Write down everything worrying you, then close the notebook.", "time_estimate": "5 min", "reward_amount": 12},
        {"title": "Sacred Reading", "description": "Read from a spiritual or philosophical text that guides you.", "time_estimate": "5 min", "reward_amount": 12},
        {"title": "Evening Reflection", "description": "Reflect on your day. What went well? What are you grateful for?", "time_estimate": "5 min", "reward_amount": 12},
        {"title": "Self-Forgiveness", "description": "Think of something you regret. Offer yourself forgiveness.", "time_estimate": "5 min", "reward_amount": 15},
        {"title": "Compassion Practice", "description": "Think of someone suffering and send them compassion.", "time_estimate": "5 min", "reward_amount": 12},
        {"title": "Letting Go Ritual", "description": "Write what you want to release on paper. Tear it up.", "time_estimate": "5 min", "reward_amount": 15},
        {"title": "Wisdom Seeking", "description": "Ask yourself: What do I need to learn from this situation?", "time_estimate": "5 min", "reward_amount": 12},
        {"title": "Values Reflection", "description": "Reflect on your top 3 values. Are you living by them?", "time_estimate": "5 min", "reward_amount": 12},
        {"title": "Purpose Pondering", "description": "Spend 5 minutes thinking about your life's purpose.", "time_estimate": "5 min", "reward_amount": 15},
        
        # 10+ min tasks
        {"title": "Guided Meditation", "description": "Follow a 10-minute guided meditation.", "time_estimate": "10 min", "reward_amount": 20},
        {"title": "Deep Journaling", "description": "Write deeply about a question or feeling for 15 minutes.", "time_estimate": "15 min", "reward_amount": 22},
        {"title": "Morning Ritual", "description": "Complete your morning spiritual practice.", "time_estimate": "15 min", "reward_amount": 22},
        {"title": "Evening Ritual", "description": "Complete your evening spiritual practice.", "time_estimate": "15 min", "reward_amount": 22},
        {"title": "Meditation Session", "description": "Sit in meditation for 15-20 minutes.", "time_estimate": "20 min", "reward_amount": 25},
        {"title": "Prayer Time", "description": "Dedicate 15 minutes to prayer or spiritual connection.", "time_estimate": "15 min", "reward_amount": 22},
        {"title": "Nature Immersion", "description": "Spend 20 minutes fully present in nature.", "time_estimate": "20 min", "reward_amount": 25},
        {"title": "Spiritual Reading", "description": "Read spiritual or philosophical texts for 20 minutes.", "time_estimate": "20 min", "reward_amount": 22},
        {"title": "Gratitude Practice Extended", "description": "Write extensively about what you're grateful for.", "time_estimate": "15 min", "reward_amount": 20},
        {"title": "Life Review", "description": "Reflect on your life journey and lessons learned.", "time_estimate": "20 min", "reward_amount": 25},
        {"title": "Intention Setting Ceremony", "description": "Set intentions for the coming month with ritual.", "time_estimate": "20 min", "reward_amount": 25},
        {"title": "Forgiveness Practice Extended", "description": "Deep forgiveness work for yourself or others.", "time_estimate": "20 min", "reward_amount": 25},
        {"title": "Contemplation Walk", "description": "Walk slowly and contemplatively for 20 minutes.", "time_estimate": "20 min", "reward_amount": 22},
        {"title": "Spiritual Community", "description": "Connect with your spiritual community online or in person.", "time_estimate": "30 min", "reward_amount": 25},
        {"title": "Service Planning", "description": "Plan how you can serve others this week.", "time_estimate": "15 min", "reward_amount": 20},
    ],
    
    "creativity": [
        # Quick 1-3 min tasks
        {"title": "Doodle Break", "description": "Grab a pen and doodle whatever comes to mind for 3 minutes.", "time_estimate": "3 min", "reward_amount": 8},
        {"title": "Write 3 Ideas", "description": "Write down 3 creative ideas. They don't have to be good!", "time_estimate": "3 min", "reward_amount": 10},
        {"title": "Take a Photo", "description": "Take a creative photo of something around you.", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Word Association", "description": "Pick a random word and write 10 words it makes you think of.", "time_estimate": "2 min", "reward_amount": 5},
        {"title": "Describe Your Surroundings", "description": "Write a creative description of where you are right now.", "time_estimate": "3 min", "reward_amount": 10},
        {"title": "Creative Observation", "description": "Look at an ordinary object and think of 5 unusual uses for it.", "time_estimate": "3 min", "reward_amount": 10},
        {"title": "Write a Haiku", "description": "Write a haiku (5-7-5 syllables) about your current mood.", "time_estimate": "3 min", "reward_amount": 10},
        {"title": "Dream Capture", "description": "Write down a dream you remember, or imagine one.", "time_estimate": "3 min", "reward_amount": 8},
        {"title": "New Perspective", "description": "Look at something from a different angle. What do you notice?", "time_estimate": "2 min", "reward_amount": 5},
        {"title": "Sensory Focus", "description": "Close your eyes and describe what you hear, smell, and feel.", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Quick Sketch", "description": "Sketch something in front of you in under 2 minutes.", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Metaphor Game", "description": "Describe your current mood as a weather pattern.", "time_estimate": "2 min", "reward_amount": 5},
        {"title": "Create a Meme", "description": "Think of a funny meme idea about your day.", "time_estimate": "3 min", "reward_amount": 8},
        {"title": "Recipe Invention", "description": "Invent a new recipe or food combination (don't have to make it!).", "time_estimate": "3 min", "reward_amount": 10},
        {"title": "Name Generator", "description": "Come up with 5 creative names for a fictional business.", "time_estimate": "3 min", "reward_amount": 8},
        {"title": "What If?", "description": "Write down 3 'What if?' questions about anything.", "time_estimate": "3 min", "reward_amount": 10},
        {"title": "Inspiration Hunt", "description": "Find one thing around you that inspires you. Why?", "time_estimate": "3 min", "reward_amount": 8},
        {"title": "Color Story", "description": "Pick a color and list 10 things that represent it.", "time_estimate": "2 min", "reward_amount": 5},
        {"title": "Emoji Story", "description": "Tell a story using only 10 emojis.", "time_estimate": "2 min", "reward_amount": 5},
        {"title": "Sound Description", "description": "Listen to a sound and describe it in 3 different ways.", "time_estimate": "2 min", "reward_amount": 5},
        
        # 4-5 min tasks
        {"title": "Listen to New Music", "description": "Listen to a song from a genre you don't usually explore.", "time_estimate": "4 min", "reward_amount": 8},
        {"title": "Color Something", "description": "Color, paint, or sketch something for 5 minutes.", "time_estimate": "5 min", "reward_amount": 12},
        {"title": "Mind Map", "description": "Create a mind map about a topic you're interested in.", "time_estimate": "5 min", "reward_amount": 12},
        {"title": "Rearrange Something", "description": "Rearrange items on your desk or in a room. Fresh perspective!", "time_estimate": "5 min", "reward_amount": 10},
        {"title": "Write a Story Start", "description": "Write the first paragraph of a story. Any story!", "time_estimate": "5 min", "reward_amount": 15},
        {"title": "Playlist Creation", "description": "Create a short playlist for a specific mood or activity.", "time_estimate": "5 min", "reward_amount": 10},
        {"title": "Letter to Future Self", "description": "Write a short letter to yourself 1 year from now.", "time_estimate": "5 min", "reward_amount": 15},
        {"title": "Opposite Day", "description": "Think of a problem and brainstorm the opposite solution.", "time_estimate": "5 min", "reward_amount": 10},
        {"title": "Poetry Attempt", "description": "Write a short poem about anything. No rules!", "time_estimate": "5 min", "reward_amount": 12},
        {"title": "Collage Planning", "description": "Plan a collage of images that represent your current life.", "time_estimate": "5 min", "reward_amount": 10},
        {"title": "Dialogue Writing", "description": "Write a short dialogue between two characters.", "time_estimate": "5 min", "reward_amount": 12},
        {"title": "Invention Idea", "description": "Invent something that would solve a daily annoyance.", "time_estimate": "5 min", "reward_amount": 12},
        {"title": "Texture Hunt", "description": "Find and photograph 5 interesting textures.", "time_estimate": "5 min", "reward_amount": 10},
        {"title": "Pattern Creation", "description": "Create a simple repeating pattern by drawing.", "time_estimate": "5 min", "reward_amount": 10},
        {"title": "Song Rewrite", "description": "Rewrite the lyrics of a song you know to be about something else.", "time_estimate": "5 min", "reward_amount": 12},
        {"title": "Character Creation", "description": "Create a fictional character with name, traits, and backstory.", "time_estimate": "5 min", "reward_amount": 12},
        {"title": "Dream Design", "description": "Design your dream room, house, or space in words or sketches.", "time_estimate": "5 min", "reward_amount": 12},
        {"title": "Word Invention", "description": "Invent 3 new words and their definitions.", "time_estimate": "5 min", "reward_amount": 10},
        {"title": "Rebrand Something", "description": "Think of how you'd rebrand a common product.", "time_estimate": "5 min", "reward_amount": 12},
        {"title": "Memory Sketch", "description": "Sketch a scene from a happy memory.", "time_estimate": "5 min", "reward_amount": 12},
        
        # 10+ min tasks
        {"title": "Free Writing", "description": "Write for 10 minutes without stopping. Don't edit!", "time_estimate": "10 min", "reward_amount": 18},
        {"title": "Art Practice", "description": "Spend 15 minutes practicing an art form you enjoy.", "time_estimate": "15 min", "reward_amount": 20},
        {"title": "Creative Challenge", "description": "Set a creative constraint and work within it for 15 minutes.", "time_estimate": "15 min", "reward_amount": 20},
        {"title": "Music Discovery", "description": "Explore new music for 15 minutes.", "time_estimate": "15 min", "reward_amount": 18},
        {"title": "Photography Walk", "description": "Go for a 15-minute walk taking creative photos.", "time_estimate": "15 min", "reward_amount": 20},
        {"title": "Writing Sprint", "description": "Write as much as you can on one topic for 15 minutes.", "time_estimate": "15 min", "reward_amount": 20},
        {"title": "Sketching Session", "description": "Sketch multiple things for 15 minutes.", "time_estimate": "15 min", "reward_amount": 20},
        {"title": "DIY Project Start", "description": "Start a small DIY or craft project.", "time_estimate": "20 min", "reward_amount": 22},
        {"title": "Learn a Creative Skill", "description": "Watch a tutorial and practice a new creative skill.", "time_estimate": "20 min", "reward_amount": 22},
        {"title": "Creative Reading", "description": "Read creative work for inspiration.", "time_estimate": "20 min", "reward_amount": 20},
        {"title": "Brainstorm Session", "description": "Dedicated brainstorming on a project or idea.", "time_estimate": "20 min", "reward_amount": 22},
        {"title": "Instrument Practice", "description": "Practice a musical instrument for 15-20 minutes.", "time_estimate": "20 min", "reward_amount": 22},
        {"title": "Digital Art Creation", "description": "Create something using digital art tools.", "time_estimate": "20 min", "reward_amount": 22},
        {"title": "Story Development", "description": "Develop a story idea with plot, characters, setting.", "time_estimate": "20 min", "reward_amount": 25},
        {"title": "Creative Collaboration", "description": "Work on a creative project with someone else.", "time_estimate": "30 min", "reward_amount": 25},
    ],
    
    "health": [
        # Quick 1 min tasks
        {"title": "Drink Water Now", "description": "Drink a full glass of water right now. Your body needs it!", "time_estimate": "1 min", "reward_amount": 3},
        {"title": "Posture Check", "description": "Sit up straight, shoulders back, feet flat. Hold for 30 seconds.", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Eye Break", "description": "Look away from screens. Focus on something 20 feet away for 20 seconds.", "time_estimate": "1 min", "reward_amount": 3},
        {"title": "Deep Breaths", "description": "Take 5 deep belly breaths. Inhale through nose, exhale through mouth.", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Caffeine Check", "description": "If it's afternoon, skip the coffee. Choose water or tea instead.", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Screen-Free Zone", "description": "Designate no screens in your bedroom tonight.", "time_estimate": "1 min", "reward_amount": 8},
        {"title": "Veggie Goal", "description": "Commit to eating one extra serving of vegetables today.", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Sleep Intention", "description": "Set a bedtime for tonight and commit to it.", "time_estimate": "1 min", "reward_amount": 8},
        {"title": "Stress Release", "description": "Tense all muscles for 5 seconds, then release. Repeat 3 times.", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Limit Sugar", "description": "Skip one sugary item you would normally have today.", "time_estimate": "1 min", "reward_amount": 8},
        {"title": "Wash Hands", "description": "Wash your hands properly for 20 seconds. Sing Happy Birthday!", "time_estimate": "1 min", "reward_amount": 3},
        {"title": "Alcohol-Free Evening", "description": "Skip alcohol tonight. Your sleep will be better!", "time_estimate": "1 min", "reward_amount": 10},
        {"title": "Gratitude for Body", "description": "Thank your body for one thing it does well for you.", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "One Glass Less", "description": "If you drink soda, skip one serving today. Choose water!", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Early Wind-Down", "description": "Start your bedtime routine 15 minutes earlier tonight.", "time_estimate": "1 min", "reward_amount": 8},
        {"title": "Jaw Relax", "description": "Notice if you're clenching your jaw. Relax it now.", "time_estimate": "1 min", "reward_amount": 3},
        {"title": "Shoulder Drop", "description": "Notice if shoulders are raised. Drop them and relax.", "time_estimate": "1 min", "reward_amount": 3},
        {"title": "Blink Break", "description": "Blink 20 times slowly to refresh your eyes.", "time_estimate": "1 min", "reward_amount": 3},
        {"title": "Tomorrow's Water Goal", "description": "Set a water intake goal for tomorrow.", "time_estimate": "1 min", "reward_amount": 5},
        {"title": "Fruit Commitment", "description": "Commit to eating one piece of fruit today.", "time_estimate": "1 min", "reward_amount": 5},
        
        # 2-3 min tasks
        {"title": "Stand Up", "description": "If you've been sitting, stand up and walk around for 2 minutes.", "time_estimate": "2 min", "reward_amount": 5},
        {"title": "Fresh Air", "description": "Step outside and take 10 deep breaths of fresh air.", "time_estimate": "2 min", "reward_amount": 5},
        {"title": "Floss", "description": "Floss your teeth right now. Your gums will thank you!", "time_estimate": "2 min", "reward_amount": 5},
        {"title": "Stretch at Desk", "description": "Do 3 desk stretches: neck, shoulders, and back.", "time_estimate": "2 min", "reward_amount": 5},
        {"title": "Mental Health Check", "description": "Rate your mood 1-10. What could improve it by 1 point?", "time_estimate": "2 min", "reward_amount": 8},
        {"title": "Track a Meal", "description": "Write down what you ate for your last meal. Awareness helps!", "time_estimate": "2 min", "reward_amount": 5},
        {"title": "Healthy Snack", "description": "Eat a piece of fruit or a handful of nuts.", "time_estimate": "3 min", "reward_amount": 8},
        {"title": "Hand Massage", "description": "Give yourself a 2-minute hand massage. Release tension!", "time_estimate": "2 min", "reward_amount": 5},
        {"title": "Face Wash", "description": "Wash your face with cool water. Refreshing!", "time_estimate": "2 min", "reward_amount": 5},
        {"title": "Neck Stretches", "description": "Gently stretch your neck in all directions.", "time_estimate": "2 min", "reward_amount": 5},
        {"title": "Ankle Pumps", "description": "If sitting, pump your ankles up and down to improve circulation.", "time_estimate": "2 min", "reward_amount": 5},
        {"title": "Belly Breathing", "description": "Practice deep belly breathing for 2 minutes.", "time_estimate": "2 min", "reward_amount": 5},
        {"title": "Eye Palming", "description": "Warm palms by rubbing, place over closed eyes. Relax 2 minutes.", "time_estimate": "2 min", "reward_amount": 5},
        {"title": "Gratitude Body Scan", "description": "Thank different body parts for what they do for you.", "time_estimate": "3 min", "reward_amount": 8},
        {"title": "Vitamin Check", "description": "Take any vitamins or supplements you may have missed.", "time_estimate": "2 min", "reward_amount": 5},
        {"title": "Water Refill", "description": "Refill your water bottle so it's ready for the day.", "time_estimate": "2 min", "reward_amount": 3},
        {"title": "Teeth Brushing Timer", "description": "Brush your teeth for a full 2 minutes.", "time_estimate": "2 min", "reward_amount": 5},
        {"title": "Stairs Choice", "description": "Take the stairs instead of the elevator today.", "time_estimate": "3 min", "reward_amount": 8},
        {"title": "Parking Far", "description": "Park farther away to get extra steps.", "time_estimate": "3 min", "reward_amount": 5},
        {"title": "Standing Break", "description": "Stand for 3 minutes. Walk around if possible.", "time_estimate": "3 min", "reward_amount": 5},
        
        # 5 min tasks
        {"title": "Sunshine Break", "description": "Get 5 minutes of sunlight if possible. Vitamin D boost!", "time_estimate": "5 min", "reward_amount": 10},
        {"title": "Health Appointment", "description": "Schedule a health checkup or appointment you've been putting off.", "time_estimate": "5 min", "reward_amount": 15},
        {"title": "Meal Planning", "description": "Plan your meals for tomorrow.", "time_estimate": "5 min", "reward_amount": 12},
        {"title": "Sleep Environment", "description": "Make your bedroom more conducive to sleep.", "time_estimate": "5 min", "reward_amount": 12},
        {"title": "Hydration Planning", "description": "Plan how you'll get enough water today.", "time_estimate": "5 min", "reward_amount": 10},
        {"title": "Healthy Recipe Search", "description": "Find one healthy recipe you'd like to try this week.", "time_estimate": "5 min", "reward_amount": 10},
        {"title": "Medicine Cabinet Audit", "description": "Check expiration dates on medicines and supplements.", "time_estimate": "5 min", "reward_amount": 10},
        {"title": "Stress Journaling", "description": "Write about what's stressing you and how to address it.", "time_estimate": "5 min", "reward_amount": 12},
        {"title": "Sleep Tracking Review", "description": "Review your sleep patterns from this week.", "time_estimate": "5 min", "reward_amount": 10},
        {"title": "Ergonomic Check", "description": "Check and adjust your workstation ergonomics.", "time_estimate": "5 min", "reward_amount": 12},
        {"title": "Relaxation Practice", "description": "Practice progressive muscle relaxation.", "time_estimate": "5 min", "reward_amount": 12},
        {"title": "Health Goal Review", "description": "Review your health goals. Are you on track?", "time_estimate": "5 min", "reward_amount": 10},
        {"title": "Portion Awareness", "description": "Eat your next meal mindfully, paying attention to portions.", "time_estimate": "5 min", "reward_amount": 10},
        {"title": "Phone Detox Start", "description": "Put your phone in another room for the next hour.", "time_estimate": "5 min", "reward_amount": 12},
        {"title": "Healthy Swap", "description": "Replace one unhealthy food with a healthier option today.", "time_estimate": "5 min", "reward_amount": 10},
        
        # 10+ min tasks
        {"title": "Mindful Eating", "description": "Eat your next meal slowly, savoring each bite.", "time_estimate": "10 min", "reward_amount": 15},
        {"title": "Relaxation Session", "description": "15 minutes of dedicated relaxation.", "time_estimate": "15 min", "reward_amount": 20},
        {"title": "Meal Prep", "description": "Prepare healthy food for tomorrow.", "time_estimate": "20 min", "reward_amount": 22},
        {"title": "Health Research", "description": "Research a health topic you want to improve.", "time_estimate": "15 min", "reward_amount": 18},
        {"title": "Cooking Practice", "description": "Cook a healthy meal from scratch.", "time_estimate": "30 min", "reward_amount": 25},
        {"title": "Doctor Visit", "description": "Attend a scheduled health appointment.", "time_estimate": "60 min", "reward_amount": 25},
        {"title": "Sleep Optimization", "description": "Research and implement better sleep practices.", "time_estimate": "20 min", "reward_amount": 22},
        {"title": "Stress Management Plan", "description": "Create a plan for managing your stress.", "time_estimate": "20 min", "reward_amount": 22},
        {"title": "Healthy Shopping", "description": "Shop for healthy foods and ingredients.", "time_estimate": "30 min", "reward_amount": 25},
        {"title": "Mental Health Practice", "description": "Practice a mental health technique for 15 minutes.", "time_estimate": "15 min", "reward_amount": 20},
        {"title": "Body Care Routine", "description": "Complete a full self-care routine for your body.", "time_estimate": "20 min", "reward_amount": 22},
        {"title": "Health Tracking Setup", "description": "Set up tracking for a health metric you want to improve.", "time_estimate": "15 min", "reward_amount": 18},
        {"title": "Nutrition Learning", "description": "Learn about nutrition for 15 minutes.", "time_estimate": "15 min", "reward_amount": 18},
        {"title": "Rest Day", "description": "Take a proper rest day for recovery.", "time_estimate": "30 min", "reward_amount": 25},
        {"title": "Digital Detox", "description": "Spend 30 minutes completely screen-free.", "time_estimate": "30 min", "reward_amount": 25},
    ],
}

# Energy-based modifiers
ENERGY_MODIFIERS = {
    "high": ["burpees", "high knees", "jumping", "walk", "stair", "run", "dance", "sprint", "power"],
    "low": ["breathing", "stretch", "drink water", "mindful", "gratitude", "sit", "reflect", "pause", "gentle", "relax"],
    "medium": []  # No filter, use all
}

# Time-based filtering
TIME_FILTERS = {
    "5min": 5,
    "15min": 15,
    "30min": 30,
    "60min": 60,
}

def get_time_minutes(time_str: str) -> int:
    """Convert time estimate string to minutes"""
    if "min" in time_str:
        return int(time_str.replace(" min", "").replace("min", ""))
    return 5  # Default
